[project]
name = "bloom-spike"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "django>=5.2,<5.3",
    "django-tailwind>=4.2.0",
    "wagtail>=7.1,<7.2",
]
