# Auto-generated by build_tailwind_from_content command
DYNAMIC_CLASSES = ['btn btn-accent', 'btn btn-error', 'btn btn-info', 'btn btn-neutral', 'btn btn-primary', 'btn btn-secondary', 'btn btn-success', 'btn btn-warning']
