# Generated by Django 5.2.6 on 2025-09-30 07:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('html', 0)], blank=True, block_lookup={0: ('cms.models.blocks.RawHTMLBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_home',
            field=models.CharField(default='', max_length=255),
        ),
    ]
