# Generated by Django 5.2.6 on 2025-10-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_title_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title_home',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
